<!DOCTYPE html>
<html lang="cs">
    <head>
        <meta charset="utf-8">
    </head>
<body>
<?php
require "data_1.php";

$jed11="SG t�my zocelen� ob�anskou v�lkou za�ali znovu tr�novat nov� jednotky. Samotn� SG t�my se v�novaly sp�e sabot��m, pr�zkumu a diplomacii, ale v�ilo se ozna�en� SG t�m �i SG �eta pro celou p�chotu Spojen� Zem�. Sou�asn� v�zbroj se sest�v� z pu�ek M-42, Steyr�, P-90 a Smartgun� a nov�ch elektronick�ch p��stroj�. �lenov� SG  t�m� nyn� za�ali tr�novat nov� jednotky pro n� se v�ilo ozna�en� SG �eta.";
$jed12="Kombinovan� jednotky st�ha�ek F/A-302 Jerrymouse a uko�ist�n�ch i nov�ch imperi�ln�ch tank� M-99 B Turok. Jednotky p�i p��m� bojov� operace, front�ln� �toky, d�lost�eleckou podporu. Jerrymouse nejen �e m��e sv�mi st�elami a lasery ��inn� ni�it pozemn� jednotky, ale jeho dolet a man�vrovatelnost mu umo��uje zasahovat i c�le ve vesm�r�, od mate�sk�ch lod� a� po letky �to�n�ch letoun�.";
$jed13="D�ky ob�ansk� v�lce byli in�en��i nuceni sestrojit lep�� model Atomov� bomby. Obohacen� naquadahem je schopn� zni�it velk� �zem�. Mnoho lid� a budov padne pokud SDI nedok�� sest�elit v�echny tyto bomby. Jedinou prozat�mn� v�hodou je po��d relativn� pomalost t�chto bomb. Ale s nov�mi v�robnami jsou nyn� lid� schopni pos�lat tyto posly smrti po tis�c�ch.";
$jed14="Po padl�m legend�rn�m presidentovi Spojen� Zem� a pozd�j��m v�dci Syn� Zem� byla pojmenov�na vylep�en� verze BC-303. T��da Rici disponuje nov� velk�m hang�rem pro 12 st�ha�ek Jerrymouse. D�le m� rychlen� motory, v�t�� palebnou s�lu a pro v�sadkov� operace m� na z�di tak� vylo�ovac� lo�. Celkov� se jedn� o k dokonalosti doveden� Prometheus. Vzhledem k ztr�t�m Imperi�ln�ch lod� Superior i Wardog, jsou Rici nad�le hlavn� lod� Zem�.";
$bud11="Mnoho imperi�ln�ch m�st bylo obsazeno. Po v�lce minist�i a guvern��i zjistili, �e t�chto m�st je mnohem v�ce ne� m�st Syn�. Nedalo se ale p�i sou�asn�ch prost�edc�ch nic d�lat, m�sta Spojen� Zem� jsou stejn� jako b�vala m�sta Imperi�ln� Zem�. �ivotn� �rove� se s vakcinac� toll�nsk�mi medikamenty zlep�ila, stejn� jako s obnoven�m infrastruktury Spojen� Zem�. P�esto maj� ale dal�� generace dost pr�ce, ne� v�e naprav�";
$bud12="Stejn� jako m�sta, i rafin�rie naquadahu p�evl�daly. Mnoho obchodn�k� zanechalo l�t�n� mezi soustavami, pir�t�n� a pa�ov�n�, d�ky kter�mu Synov� z�skali tolik bohatstv�, a rad�ji se vr�tili k bezpe�n�j�� ob�iv�, provozov�n� rafin�ri�. Naquadah se stal z�kladn� platebn� jednotkou galaxie. Za naquadah si m��ete po��dit cokoliv se v�m zamane, od j�dla a� po lod�. Stejn� tak i cokoliv za n�j m��ete prod�vat�";
$bud13="Zde plat� p�esn� opak situace s m�sty a rafin�riemi. Synov� zv�t�zili, jejich vojska proto nep�eb�rali p��li� z�kladny Imp�ria. St�lo se to, co se st�t muselo, z�kladny Syn� se staly z�kladnami Spojen� Zem�. Na mnoha b�z�ch neprob�hly tak�ka ��dn� �pravy, st�le tak funguj� stejn�, jako za ob�ansk� v�lky. �asto jsou kryt� maskovac�mi s�t�mi, pln� Stinger� a Patriot� proti letectvu, s kulometn�mi hn�zdy na ka�d�m rohu.";
$bud14="Projekt obrany proti hlavic�m m�li lid� na�t�st� u� rozpracovan�, kdy� p�i�el pr�lom v oblasti 3.typ� zbran�. Mohli tak snadno postavit mnoho SDI. Tyto komplexy jsou mmj. vybaven� raketami Patriot pokud by se c�l dostal bl�zko, a raketami Excalibur, pro c�le vzd�len� a� 300 000km. ";
$bud15="Ob�ansk� v�lka skon�ila. V�da znovu nemus� nutn� slou�it vojenstv�. S t�mto faktem se tis�ce v�dc� znovu d�ky hv�zdn�m bran�m vr�tili do prozkoum�v�n� jin�ch syst�m�, planet, fyzik�ln�ch jev�. Dne�n�m trendem je vlastn� v�deck� stanice daleko od m�st. Znovu vyr�staj� archeologick� vesni�ky, stanovi�t� pro pr�zkum mimozemsk� fauny a fl�ry, b�ze na neobyvateln�ch planet�ch a m�s�c�ch, kosmick� stanice." ;
$bud16="A� u� se jedn� o z�bavn� slu�by, jako t�eba provozovatele bezdr�tov�ho Internetu, nebo o sympatick� obchody, kina �i l�zn�, v�dy to zvedne mor�lku ob�an�. Spr�vn� v�dcov� jsou si toho v�domi. Mili�ny lid� zde naleznou zam�stn�n�, tak� dal�� miliardy zde naleznou odpo�inek. Vyu�ije�-li t�chto zp�sob� zvednut� mor�lky, bude� spr�vn� vl�dnout. ";

$jed51=Addslashes("Mnoho z nich je�t� ned�vno pat�ilo ke goa'uld�m nebo jin� rase. A�koliv se to nezd�, propojen� se symbiontem  p�in�� mnoho klad�, v�ce ne� propojen� s tok'rou. Proto tis�ce lid� migruj� sem, k jaff�m. Dostanou vlastn� v�zbroj, ne v�dy v�ak zbroj, vlastn� zat'nik'atel, ty�ovku, n�� �i intar. Jaff�t� velitel� jsou vybaven� i osobn�m �t�tem. V�ichni se ale nau�� jak bojovat nabl�zko, mu� proti mu�i. To a jejich v�ra jim jednou mohou zachr�nit �ivot.");
$jed52=Addslashes("Norm�ln� jaffov�, kte�� prok�� v boji mimo��dn� schopnosti a tak� mimo��dnou oddanost ve sv� v��e, maj� tu �est a povinnost slou�it v elitn�ch odd�lech sebevra�edn�ch v�le�n�k�. Vybaven� pouze lehkou �i ��dnou zbroj�, ty�ov�mi zbran�mi, naquadahovou bombou a svou odvahou, pou�t�j� se tyto jednotky na nep��tele hlava nehlava. Ne v�dy v�ichni zahynou�  odd�ly jsou vybaveny tak� maskovan�mi teltaky a bojov�mi kluz�ky pro v�sadky na lod�ch.");
$jed53=Addslashes("Informace o reb�lii se ���� galaxi� jako zvuk polnice. Goa'uldi se sna�� p��znivce rebel� zviklat  l�emi o tom, �e vyhladili tok'ry. Ale ani to jim a dal��m bezv�rc�m nepom��e! V�ichni budou osvobozeni! Tyto fanatick� skupiny jaff� vstoup� do jejich m�st a vesnic, a jaffy osvobod�. Nebo nab�dnou civilist�m st�t se jaffy!  A�koliv se tento druh boje zbyl�m tok'r�m a ani mnoha jin�m spojenc�m rebelsk�ch jaff� nel�b�, nic nenad�laj�");
$jed54=Addslashes("Mnoho al-kesh� a bombardovac�ch teltak� bylo zni�eno b�hem P�du tok'r�. Jaffov� jich sice zbytek horliv� za�ali vyu��vat, ale to na rostouc� n�roky nesta�ilo. Mistr Bra'tac proto navrhl nov� stroj. Z jeho dob u Apophise poch�zel p�edch�dce �to�n�ch letoun�. Byl levn�j�� a m�n� n�ro�n�j�� ne� sou�asn� goa'uldsk� letouny. Rebel�t� jaffov� za�ali s hromadnou v�robou. Brzy ji� budou moct opanovat i vesm�r.");

$bud51=Addslashes("Mnoho tok'r� padlo. Jejich odkaz ale �ije d�le. Tak jako mili�ny jaff� �ij� v b�val�ch gigantick�ch tok'ersk�ch m�stech, tak i jaffov� vybudovali m�sta nov�. A v neposledn� �ad� tak� obsadili mnoh� goa'uldsk� m�sta. M�sta jaff� jsou pln� oddan�ch a� fanatick�ch obyvatel. Pal�ce, chr�my, Kcheb�t� kn�� na ulic�ch, ale i tr�i�t�, domy, slumy a kas�rna. To jsou jaffsk� m�sta, v okrajov�ch perif�ri�ch �ij� v ghettsk�ch tunelech zbyl� tok'rov�.");
$bud52=Addslashes("Tyto tunely, poz�statky P�du tok'r�, z�skaly nyn� jedine�n� vyu�it�! D�ky mno�stv� krystal� pro tvo�en� tok'ersk�ch tunel� mohou nyn� jaff�t� d�ln�ci snadno a bezpe�n� t�it naquadah i hluboko pod zem�. Vysp�l� technologie lokalizace naquadahu umo�n� bezpe�nou podzemn� t�bu, tolik pot�ebnou pro reb�lii. Av�ak, tunely mus� v�st na povrch klasiky, ne pomoc� transportn�ch kruh�. To se m��e uk�zat jako nev�hoda ..");
$bud53=Addslashes("Traduje se, �e jaffov� jsou ve sv�m boji za svobodu fanati�t�. Jejich odvaha hrani�� a� s fanati�nost�. Zde se montuj� kluz�ky a spravuj� zbyl� al-keshe. Zde se u�� jaffov� jak konvertovat ciz� rasy na svou stranu, i jak se probojovat s naquadahovou n�lo�� do centra nep��telsk� arm�dy �i k j�dru ciz� lodi. Zde se jaffov� u�� st��let z ty�ovek, bojovat mu� proti mu�i a pilotovat kluz�ky!");
$bud54=Addslashes("Gigantick� pulsn� zbran� nam��en� na nebesa. Konstrukc� vych�zej� z ty�ov�ch zbran� (odtud pulsn� technologie), ale jsou mnohon�sobn� v�t��. Zam��ovac� syst�my jsou to nejlep��, co tok'er�t� agenti a jaff�t� rebelov� mohli goa'uld�m ukr�st. Budova je vcelku dob�e br�n�n� jednotkou jaff� i hlubok�m p��kopem. Nicm�n� jsou ji vyt�k�ny fat�ln� nedostatky v obran� proti stiha��m - kluz�ky mohou budovu snadno zni�it!");
$bud55=Addslashes("V trosk�ch laborato�� tok'r� se zrodily i laborato�e jaff�. Tyto m�stnosti jsou hluboko pod zem�, mnohdy vytvo�en� pomoc� tok'ersk�ch krystal� na hlouben� tunel�. S povrchem jsou spojeny pomoc� transportn�ch kruh�. Je to snad jedin� m�sto v jaffsk� reb�lii, kde jsou po�ty jaff� a tok'r� i po P�du tok'r� vyrovnan�. Zbyl� tok'rov� zde pracuj� spolu s jaffy a zajat�mi goa'uldy na technologi�ch, kter� by jednou mohly zachr�nit celou rasu�");
$bud56=Addslashes("Jaffov� maj� r�di odpo�inek. Mnoha lidem (asgard�m, oanessan�m, �) se m��e zd�t, �e se ale nemaj� jak uvolnit. To ale jenom dokazuje, �e jaffy neznaj�! V t�chto stanech se sk�t� v�e, co dok�e jaffu, a nejen jeho, rozpt�lit. Vodn� d�mky, n�poje mnoha chut� (pozor, jaffov� nekonzumuj� alkohol!), kurtiz�ny, ter�e pro ty�ov� zbran�, komunika�n� koule i mno�stv� sv��ek kvalitn� pro kel'no'reem.");

$jed101=Addslashes("Plavci piln� cvi�ili b�hem dob Aliance. Mnoho se nau�ili od elitn�ch plavc�, mnoh� od bojovn�k� reetou a trha��. Zdokonalili sv� bojov� um�n�, znalost pl�en�, sv� zbran� vylep�ili. Nov� maj� tak� energetick� �t�t kolem sv� postavy a brn�n� z odoln� organick� hmoty jen� se sama obnovuje. Po rozpadu Aliance jsou oni, m�rn� zfanatizov�ni, jsou oni nad�j� oanessansk� ��e. Oni jsou jej� poslov�.");
$jed102=Addslashes("Jedna z m�la novinek v oanessk� ��i. Ve v�zbroji t�to nejsiln�j�� stiha�ky v galaxii je baterie plasmov�ch d�l, podsv�teln� torp�da s n�pln� naquadrie a uranu a tak� vy�azovac� paprsky. �t�ty jsou modifikovan� oanessansk� �t�ty �lunku, pos�dka pat�� k elit� cvi�en� po des�tky let! Tyto lod� jsou schopny atmosf�rick�ho i mezihv�zdn�ho letu a jejich bojov�m c�lem je podporovat arm�dy plavc� a v�le�n�k� i p��m� souboj po boku Traval.");
$jed103=Addslashes("Tato zbra� disponuje technologi� podobnou seizmick� bomb� Tok'r�. Tato technologie byla op�t zakoupena od asgardsk�ch p�ekupn�k� b�hem virov� infekce. Na rozd�l od seizmick� bomby ale exploduje pod hladinou mo�e a zp�sob� tak obrovskou p��livovou vlnu vysokou 300 metr�, tsunami, kter� zaplav� pob�e�n� m�sta a zp�sob� katastrof�ln� klimatick� zm�ny. Nyn� znovu ve v�zbroji Oanessan�.");
$jed104=Addslashes("Vylep�en� Travaly maj� p�esn� kulovit� tvar a jejich pr�m�r je 2 km. Zbran� jsou pulzn� plazmov� d�la.. Tak jak se rozpadla Aliance, i Cyborgov�, kdysi v�zbroj Traval, odl�tli. Povrch lod� tvo�� odoln� organick� hmota jen� se sama obnovuje. S pou�it�m nejlep��ch oanessansk�ch a fragment� reetsk�ch technologi� se tato lo� stala opravdu dokonalou.. pos�dka je vyb�r�na z Oanessansk� elity! ");
$bud101=Addslashes("P�ekr�sn� struktury m�sta Oanessan� p�itahuj� mili�ny turist�. Tyto m�sta jsou pln� �ivota, ryby plavou kolem budov, ob�an� se plav�n�m p�emis�uj� k nejbli���m budov�m. M�sta jsou stav�na v hloubk�ch do 50 metr�, proto tak� Oanessan� disponuj� velmi vysp�lou teraforma�n� technologi� nav��en� dna, aby vytvo�ili dostatek t�chto hloubek. Z dob Aliance zde st�le s�dl� mnoho reetou.");
$bud102=Addslashes("Naquadah se p�ekvapiv� ukr�v� i pod hladinami oce�n�.A proto�e oce�ny tvo�� na v�t�in� obyvateln�ch planet�ch 2/3 celkov�ho povrchu planety, jde o velmi jednoduch� m�sto pro nalezen� lo�isek. Zde pak pracuj� tis�ce hleda�� naquadahu, kte�� stejn� jako na Zemi hleda�i perel, jsou velmi bohat� odm�n�ni za nam�havou a n�ro�nou pr�ci. V posledn� dob� je v�ak mnoho z hleda�� nahrazov�no roboty.");
$bud103=Addslashes("Levn� a odoln� kas�rna pat�� k koloni�m Oanessan�. Zde jsou ubytov�ni  a vyzbrojeni Plavci, zde jsou k vid�n� os�dky i montovan� �lunky Uruku. Tyto stavby jsou podlouhl� a neust�le se vevnit� reguluje tlak vzduchu. Toto je pro p��pad napaden� kas�ren, Oanessan� vydr�� tyhle zm�ny tlaku, ale jin� rasy by byly v�n� zran�ny. Tyto kas�rna nebyly dlouho pou��v�na, ale nyn� po rozpadu Aliance se tak m� znovu st�t�");
$bud104=Addslashes("Dvoj�ata Gattlingov�ch plasmov�ch rychlopaln�ch d�l stoj� na povrchu planet a chr�n� tyto planety od zbran� hromadn�ho ni�en�. Tato technologie st�la Oanessansk� v�dce desetilet� v�zkumu, proto�e museli u�init plasmov� zbran� schopn� v�st�el� s velmi, velmi velkou kadenc� mezi v�st�ely. Ale v�sledek stoj� za to! Jejich sl�va �la a� tak daleko, �e je pou��vali i Synov� Zem�.");
$bud105=Addslashes("Oanessan�t� in�en��i v oanessansk�ch budov�ch. Tyto stavby se skr�vaj� pod hladinou mo�� a jsou skvostem. Mnoho v�dc� zde pracuje, a p�i pohledu z okna vid� p�ekr�sn� v�jevy mo�e � ryby, oanessk� stroje a dal��. Je opravdu pot�en� zde pracovat. Z toho i plyne, �e v�sledky velitele a starosty p��mo nadchnou!");
$bud106=Addslashes("Tyto o�zy klidu v Oanessansk�ch m�stech jsou proslaven�mi po cel� galaxii. Hraje zde uklid�uj�c� hudba, sv�tla jsou tlumen�, ale na zase tak, aby ne�lo ��st. Po zdech se pohupuje sv�tlo z odlesk� slunce ve vod�. A k tomu v�emu 'knihy'. Ale ne ledajak�. �etba se funguje na obr�cen�m principu vyvol�v�n� vzpom�nek - p��b�hy skoro pro��v�te, ne �tete. Tato metoda se rychle roz���ila v galaxii a vytla�uje zbyl� luxusn� nezni�en� aschensk� kav�rny.");

$jed31="Reetov� b�hem zjistili, �e na ovl�dnut� galaxie bude pot�eba je�t� mnohem v�ce! Za�ali objevovat taje genetick�ho in�en�rstv�. Vyvinuli n�hradu za nedosta�uj�c� fanatick� bojovn�ky! Pohle�te na Reetsk� bojovn�ky nov� generace! Vybaven� �ivo�i�n�mi zbran�mi, nap��klad dr�py,dok�� b�t ��inn�j�� ne� jejich star�� verze! Jejich krutost v boji je zn�m� po cel� galaxii. Davy za davem dok�� �to�it, nec�t� bolest, rychle se mno��.";
$jed32="Reetou kdysi p�ekvapily v�echny rasy kdy� za�aly bleskov�m tempem kolonizovat galaxii tak kr�tce po sv�m skoro vyhlazen�. A pr�v� v dob� nejv�t��ho �tlaku Reetou, kdy byli v oble�en� �ty� velk�ch ras, se zrodil nov� typ terorist�! Mnohem v�ce fanati�t�j��, pou��vaj�ce bojov� drogy a pos�len� podko�n�m panc��em, tito temn� neviditeln� voj�ci d�sili galaxii� a nyn�, po zlat�m v�ku Aliance i jej�m rozpadu, se tot� opakuje�";
$jed33="Nov� verze t�chto zbran� , BETA, zadala z�minku mnoha organizac�m pro lidsk� pr�va pro protesty proti jejich zav�d�n� Reetou. Ale moc platn� to nebylo�   Nov� bojov� plyny obohacen� o sm�s podobnou Antraxu nesen� sebevra�edn�m pilotem mal� rakety se staly nov�m postrachem galaxie. Zvl᚝, kdy� nosi�e bomb byly vylep�en� o oanessansk� �t�ty a piloty se stali Cyborgov�.";
$jed34="Reetsk� Biogenetika p�inesla ji� p�ed lety dal�� plod - kombinaci Reetou a stroje! Smrtonosn� eskadry tis�c� t�chto voj�k� neznaj�c�ch strach ani l�tost cestuj� na sv�ch mal�ch lod�ch kosmem a bezhlav� �to�� na sv� c�le. Jsou odoln� v��i radiaci, laser�m, mohou ��t neomezen� dlouho v prostoru bez kysl�ku s nulov�m tlakem! A samoz�ejm� jsou tak� neviditeln� zp�sobili ji� mnoho �kod.";
$bud31="Bojovn� n�lady po pora�en� ofici�ln� vl�dy Reet� opadly, av�ak po rozpadu Aliance se vracej�. Velitel� reetou hledali zp�sob, jak se v�ce vyvinout! Bylo nutn� postavit nov� m�sta! In�en��i Reetou hledali zp�soby jak zv��it budovy, voj�ci byli nad�eni z nov� kapacity m�st, terorist� z dal��ch p��le�itost� rekrutov�n�. Po rozpadu Aliance ji� nic nebr�n� reetou potla�ovat svou agresivitu!";
$bud32="Jednou slabost� Aliance bylo, �e po��d nena�la efektivn� zp�sob t�by naquadahu. Po��d t�� naquadah p�es vodn� rafinerie. �alostn� pomal� zp�sob t�by, bohu�el jedin�, kter� Aliance pova�uje za dobr��p�esto to byl pokrok od sb�r�n� naquadahu reetsk�mi sb�ra�i� nyn� ale reetou renovuj�! Pohle�te na nov� rafin�rie! Nyn� se na�i sb�ra�i ji� tolik nenapracuj� a mnoho z nich tak bude moci slou�it jako na�i voj�ci!";
$bud33="Mocn� Reetou v honb� za v�t��m imp�riem pot�ebovali v�t�� kapacitu kas�ren� Proto zah�jili velk� program p�estavby. Nov� kas�rna jsou pohodln�j�� a p�esto rozm�rn�j��. Umo��uj� lep�� tr�nink a v�uku Reetou o tom kdo je hodn� a kdo je zl�. Le�� uprost�ed obytn�ch t�n reetsk�ch m�st, co� umo��uje sn�ze rekrutovat teroristy �i p�em��ovat d�ln�ky na cyborgy a trha�e. Tyto nov� kas�rna  se stala z�kladem nov�ho imp�ria reetou.";
$bud34="V poln�ch podm�nk�ch reetsk�ch t�bor� a m�st nen� �as na vybudov�n� hi-tech obran�ch syst�m�. Je�t� ned�vno n�s chr�nili oanessansk� syst�my, ale nyn� je �as obnovit na�e vlastn� zbran�. P�esto je tento syst�m plasmov�ch d�l nam��en�ch na nebe velmi schopn�. Zru�n� reetov� jej mohou postavit rychle a levn�. Av�ak uvnit� mus� b�t velmi po�etn� pos�dka, proto�e ve�ker� zam��ov�n� prob�h� skrz myslitele a sta�e�iny reetou.";
$bud35="Tyto rozm�rn� ov�ln� budovy sk�taj� r�j pro v�echny inteligentn� reetou. Zde jim nehroz�, �e by je fanatick� jednotky mohly nedobrovoln� transformovat na trha�e �i cyborgy, zde si jich vl�da p��li� cen�. V t�chto a mnoha podobn�ch laborato��ch vznik� to, ��m se reetou tak proslavili - genov� in�en�rstv�. Zde se p�i�lo na princip chemick�ch bomb, klasick�ch bomb pro teroristy, na propojen� reetou a stroje, i na principy mutac� .. a v�zkum jen tak neskon��.";
$bud36="Teroristi�t� Reetou maj� opravdu r�di st�elbu. Jejich plasmov� pu�ky maj� silnou razanci, tak pro� je nevyzkou�et nane�isto, �ekli si v�dcov� reetou. Proto byly vybudov�ny komplexy st�elnic, kde by mohli i mal� Reetov� zkou�et sv� bojov� znalosti a ti star�� se p�ipravit na �tok na nep��tele. Dnes se tyto st�elnice st�vaj� oporou na�� rasy po rozpadu Aliance. Bu�me za n� r�di!";


MySQL_Query("update texty set jed1='$jed11',jed2='$jed12',jed3='$jed13',jed4='$jed14' where rasa=1");
MySQL_Query("update texty set mesto='$bud11',vyrobna='$bud12',kasarna='$bud13',obrana='$bud14',park='$bud16',lab='$bud15' where rasa=1");

MySQL_Query("update texty set jed1='$jed31',jed2='$jed32',jed3='$jed33',jed4='$jed34' where rasa=3");
MySQL_Query("update texty set mesto='$bud31',vyrobna='$bud32',kasarna='$bud33',obrana='$bud34',park='$bud36',lab='$bud35' where rasa=3");

MySQL_Query("update texty set jed1='$jed51',jed2='$jed52',jed3='$jed53',jed4='$jed54' where rasa=5");
MySQL_Query("update texty set mesto='$bud51',vyrobna='$bud52',kasarna='$bud53',obrana='$bud54',park='$bud56',lab='$bud55' where rasa=5");

MySQL_Query("update texty set jed1='$jed101',jed2='$jed102',jed3='$jed103',jed4='$jed104' where rasa=10");
MySQL_Query("update texty set mesto='$bud101',vyrobna='$bud102',kasarna='$bud103',obrana='$bud104',park='$bud106',lab='$bud105' where rasa=10");

Mysql_close($spojeni);
?>
</body>
</html>
